### ISSUE TITLE
[BUG]  go.mod tidy fails due to unresolved module in dd-trace-go

### ISSUE THREAD

**Issue by klaus-ziegert** [DataDog/dd-trace-go#3059]
**Version of dd-trace-go**
gopkg.in/DataDog/dd-trace-go.v1 v1.70.1

**Describe what happened:**
When adding the following import statement in a Go file:
```
package main

import _ "gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
```

and running `go get -u -t ./...` followed by `go mod tidy`, the following error occurs:

```
go: downloading k8s.io/apimachinery v0.25.5
go: downloading github.com/rogpeppe/go-internal v1.10.0
go: finding module for package go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1experimental
go: finding module for package go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/profiles/v1experimental
go: test imports
	gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer imports
	github.com/DataDog/datadog-agent/pkg/trace/stats imports
	github.com/DataDog/datadog-agent/pkg/trace/transform imports
	github.com/DataDog/datadog-agent/pkg/trace/sampler tested by
	github.com/DataDog/datadog-agent/pkg/trace/sampler.test imports
	go.opentelemetry.io/collector/processor/processortest imports
	go.opentelemetry.io/collector/pdata/testdata imports
	go.opentelemetry.io/collector/pdata/pprofile imports
	go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/profiles/v1experimental: module go.opentelemetry.io/collector/pdata@latest found (v1.22.0), but does not contain package go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/profiles/v1experimental
go: test imports
	gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer imports
	github.com/DataDog/datadog-agent/pkg/trace/stats imports
	github.com/DataDog/datadog-agent/pkg/trace/transform imports
	github.com/DataDog/datadog-agent/pkg/trace/sampler tested by
	github.com/DataDog/datadog-agent/pkg/trace/sampler.test imports
	go.opentelemetry.io/collector/processor/processortest imports
	go.opentelemetry.io/collector/pdata/testdata imports
	go.opentelemetry.io/collector/pdata/pprofile imports
	go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1experimental: module go.opentelemetry.io/collector/pdata@latest found (v1.22.0), but does not contain package go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1experimental
```

**Describe what you expected:**
I expected `go mod tidy` to resolve all module dependencies and clean up the go.mod and go.sum files without encountering unresolved dependencies.

**Steps to reproduce the issue:**
<img width="842" alt="Image" src="https://github.com/user-attachments/assets/a0c1ba20-2ee9-4e15-a4aa-7a64a2ba17b7" />

**Additional environment details (Version of Go, Operating System, etc.):**
go version go1.23.4 darwin/arm64

**Comment by c0untingNumbers** [comment]
I encountered this issue as well. Downgrading `dd-trace-go.v1` to `v1.69.1` fixed it for me. You can run `go get gopkg.in/DataDog/dd-trace-go.v1@v1.69.1` to downgrade it.

OpenTelemetry made [changes to the collector](https://github.com/open-telemetry/opentelemetry-collector/commit/33264a5408cd918cfb45fd622b99f681c67d535c#diff-2bc05093232998ce684e2f36bb0e31f3ed3416ebae10fb83f5ecbd115c5c987f ) as they changed the profile name from `v1experimental` to `v1development`. However, the datadog-agent is still using `v1experimental`. This is what is causing the issue.

The changes are in `go.opentelemetry.io/collector/pdata v1.22.0` and the datadog-agent is still using `v1.21.0` as you can see [here](https://github.com/DataDog/datadog-agent/blob/main/go.mod#L296).

**Comment by taltcher** [comment]
Hi. Is there an ETA on that issue? It is blocking us from upgrading packages in our repos. It seems like a critical issue, right? Since this version is not usable

**Comment by eliottness** [comment]
👋 Hello, happy new year and apologies everyone for the delay on this. We found a temporary fix that we merged in #3042 waiting for the right release from the agent team.

You can already try running `go get gopkg.in/DataDog/dd-trace-go.v1@release-v1.71.x`. 

We are confident in getting `v1.70.2` and `v1.71.0` with the fix by next week. Thanks for the wait everyone 🙇

**Comment by rosti-il** [comment]
I also want to know when the fix of this issue will be released. Especially now, when downgrading `gopkg.in/DataDog/dd-trace-go.v1` from `v1.70.1` to `v1.69.1` doesn't work anymore. The fix was committed (#3042) two weeks ago but not back ported to 1.70 branch. If it takes so much time to release `v1.71.0` why not to release a patch release `v1.70.2` now?

**Comment by rosti-il** [comment]
I also want to know when the fix of this issue will be released. Especially now, when downgrading `gopkg.in/DataDog/dd-trace-go.v1` from `v1.70.1` to `v1.69.1` doesn't work anymore. The fix was committed (#3042) two weeks ago but not back ported to 1.70 branch. If it takes so much time to release `v1.71.0` why not to release a patch release `v1.70.2` now?

**Comment by rosti-il** [comment]
I see https://github.com/DataDog/dd-trace-go/actions/runs/12585119784/job/35076220193 still failing with the same error, although the fix from #3042 is already applied  into that branch (`release-v1.71.x`)
```
go: datadoghq.dev/orchestrion/_integration-tests/tests/dd-span imports
	gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer imports
	gopkg.in/DataDog/dd-trace-go.v1/internal imports
	go.opentelemetry.io/collector/pdata/pprofile imports
	go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/profiles/v1experimental: module go.opentelemetry.io/collector/pdata@latest found (v1.22.0), but does not contain package go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/profiles/v1experimental
go: datadoghq.dev/orchestrion/_integration-tests/tests/dd-span imports
	gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer imports
	gopkg.in/DataDog/dd-trace-go.v1/internal imports
	go.opentelemetry.io/collector/pdata/pprofile imports
	go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1experimental: module go.opentelemetry.io/collector/pdata@latest found (v1.22.0), but does not contain package go.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1experimental
```

**Comment by eliottness** [comment]
> I see [DataDog/dd-trace-go/actions/runs/12585119784/job/35076220193](https://github.com/DataDog/dd-trace-go/actions/runs/12585119784/job/35076220193) still failing with the same error, although the fix from https://github.com/DataDog/dd-trace-go/pull/3042 is already applied into that branch (release-v1.71.x)
@rosti-il This job tests dd-trace-go against https://github.com/DataDog/orchestrion and we need to upgrade `go.opentelemetry.io/collector/pdata` manually in this repo to make this error disappear. This is what blocked `v1.70.2` last week because of a (now known to be) unrelated bug.

**Comment by eliottness** [comment]
I can confirm [dd-trace-go@v1.70.2](https://github.com/DataDog/dd-trace-go/releases/tag/v1.70.2) is now released which why I will now close this issue. Feel free to reopen it if for some reason this error comes up again.

**Comment by rosti-il** [comment]
@eliottness Thank you. The [dd-trace-go@v1.70.2](https://github.com/DataDog/dd-trace-go/releases/tag/v1.70.2) works for me!
